# Generated by Django 5.1.2 on 2024-10-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_start_date', models.DateField()),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('enquiry_closer_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('enquiry_state', models.CharField(max_length=50)),
                ('enquiry_status', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(max_length=100)),
                ('submitted_by', models.CharField(max_length=100)),
                ('resolution_summary', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ending_status', models.CharField(max_length=50)),
            ],
        ),
    ]
