# Generated by Django 5.1.2 on 2024-10-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airback', '0003_technician_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
