# Generated by Django 5.1.2 on 2024-10-19 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airback', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
